<a href="https://colab.research.google.com/github/Tahsin-20/Python-Libraries/blob/main/Pandas/Pandas(Series)/Pandas(Series).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [ ]:
import numpy as np
import pandas as pd

### Series from lists

In [ ]:
#String type series (String is called object in Pandas)
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [ ]:
#Integers
runs = [13,24,56,78,100]

runs_ser=pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [ ]:
#Custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [ ]:
#Setting a name
marks = pd.Series(marks,index=subjects,name='Tahsin er marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Tahsin er marks, dtype: int64

### Series from dictionary

In [ ]:
#Series from dic
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks,name='Tahsin er marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: Tahsin er marks, dtype: int64

### Series Attributes

In [ ]:
#size
marks_series.size

4

In [ ]:
#dtype
marks_series.dtype

dtype('int64')

In [ ]:
#name
marks_series.name

'Tahsin er marks'

In [ ]:
#Returns boolean value if unique values or not
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [ ]:
#Gives indices value
marks_series.index
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#Gives value
marks_series.values

array([ 67,  57,  89, 100])

### Series using read_csv

In [ ]:
#Reads csv files to series
subs = pd.read_csv('/content/subs.csv').squeeze('columns')
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
#With 2 cols
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze('columns')
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze('columns')
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series methods

In [ ]:
#Head and Tail (Shows preview not copying)
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
#Shows top 3 data
vk.head(3)

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [ ]:
#Shows last 10 data
vk.tail(10)

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [ ]:
#Shows random (n) data
movies.sample(5)

movie
Aisa Yeh Jahaan        Yashpal Sharma
Loveshhuda             Girish Taurani
Gulaal (film)           Kay Kay Menon
Pyare Mohan              Fardeen Khan
Anamika (2008 film)        Dino Morea
Name: lead, dtype: object

In [ ]:
#Value_counts -> movies (Frequency count)
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [ ]:
#Sort_values -> inplace
vk.sort_values(ascending=False)
vk.sort_values(ascending=False).head(1).values[0]
vk = vk.sort_values() #Sorts values inplace
vk

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [ ]:
#Sort_index -> inplace -> movies (Changes original series in alphabetical order)
movies.sort_index(ascending=False,inplace=True)

### Series Maths Methods

In [ ]:
#Count (Only no missing values)
vk.count()

np.int64(215)

In [ ]:
#Sum -> product
subs.sum()
subs.product()

np.int64(0)

In [ ]:
#mean -> median -> mode -> std -> var
print(subs.mean())
print(vk.median())
print(movies.mode())
print(subs.std())
print(vk.var())

135.64383561643837
24.0
0    Akshay Kumar
Name: lead, dtype: object
62.67502303725269
688.0024777222342

In [ ]:
#min/max
subs.max()
subs.min()

33

In [ ]:
#Provides summary about the data
subs.describe()
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

### Series Indexing

In [ ]:
#Integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

0    12
1    13
2    14
3    35
4    46
5    57
6    58
7    79
8     9
dtype: int64

In [ ]:
#Negative indexing (Only works when indices are string not otherwise)
x[-1]
movies[-1]

KeyError: -1

In [ ]:
#Slicing
vk[5:16]

match_no
207    0
135    0
130    0
211    0
106    1
204    1
113    1
77     1
1      1
5      1
75     1
Name: runs, dtype: int64

In [ ]:
#Negative slicing
vk[-5:]

match_no
164    100
120    100
123    108
126    109
128    113
Name: runs, dtype: int64

In [ ]:
movies[::2]

movie
Zor Lagaa Ke...Haiya!         Meghan Jadhav
Zindagi Tere Naam        Mithun Chakraborty
Zindagi 50-50                   Veena Malik
Zinda (film)                    Sanjay Dutt
Zid (2014 film)              Mannara Chopra
                                ...
3 Storeys                       Aisha Ahmed
3 Deewarein                Naseeruddin Shah
22 Yards                        Barun Sobti
1971 (2007 film)             Manoj Bajpayee
1920: London                  Sharman Joshi
Name: lead, Length: 750, dtype: object

In [ ]:
#Fancy indexing
vk[[1,3,4,5]]

match_no
1     1
3    13
4    12
5     1
Name: runs, dtype: int64

In [ ]:
#Indexing with labels -> fancy indexing
movies['2 States (2014 film)']

'Arjun Kapoor'

### Editing Series

In [ ]:
#Using indexing
marks_series[1] = 100
marks_series

/tmp/ipykernel_2763/2544619804.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

maths       67
english    100
science     89
hindi      100
Name: Tahsin er marks, dtype: int64

In [ ]:
#What if an index does not exist
marks_series['evs'] = 100
marks_series

maths       67
english    100
science     89
hindi      100
evs        100
Name: Tahsin er marks, dtype: int64

In [ ]:
#Slicing
runs_ser[2:4] = [100,100]
runs_ser

0     13
1     24
2    100
3    100
4    100
dtype: int64

In [ ]:
#Fancy indexing
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

0      0
1     24
2    100
3      0
4      0
dtype: int64

In [ ]:
#Using index label
movies['2 States (2014 film)'] = 'Alia Bhatt'
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)                Alia Bhatt
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

### Series with Python Functionalities

In [ ]:
#Length of row/Type of datat/Dir/Sorted in a list/max/min
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(min(subs))
print(max(subs))

365
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_cacher', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']
[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]
33
396

In [ ]:
#Type conversion
list(marks_series)

[67, 100, 89, 100, 100]

In [ ]:
dict(marks_series)

In [ ]:
#Membership operator (Only searches in indices in default)

'2 States (2014 film)' in movies

In [ ]:
'Alia Bhatt' in movies.values

In [ ]:
#Looping (Runs on values)
for i in movies.index:
  print(i)

In [ ]:
#Arithmetic Operators(Broadcasting)
#Works on all arithmatic operators
100 - marks_series

In [ ]:
#Relational Operators

vk >= 50

### Boolean Indexing on Series

In [ ]:
#Find no of 50's and 100's scored by kohli
vk[vk >= 50]

In [ ]:
#Find number of ducks
vk[vk == 0].size

In [ ]:
#Count number of day when I had more than 200 subs a day
subs[subs > 200].size

In [ ]:
#Find actors who have done more than 20 movies
num_movies = movies.value_counts()
num_movies[num_movies > 20]

### Plotting Graphs on Series

In [ ]:
subs.plot()

In [ ]:
movies.value_counts().head(20).plot(kind='bar')

In [ ]:
movies.value_counts().head(20).plot(kind='pie')

### Some Important Series Methods

In [ ]:
#Changes datatype (Reduces memory)
import sys
sys.getsizeof(vk)

In [ ]:
sys.getsizeof(vk.astype('int16'))

In [ ]:
#Find out data between a range (Both numbers included)
vk[vk.between(51,99)]

match_no
197    51
71     51
103    51
122    52
198    53
131    54
129    54
137    55
44     56
85     56
144    57
57     57
80     57
34     58
209    58
141    58
73     58
104    62
132    62
134    64
74     65
45     67
162    67
97     67
148    68
52     70
152    70
41     71
175    72
188    72
68     73
213    73
99     73
127    75
116    75
117    79
119    80
110    82
160    84
178    90
145    92
81     93
82     99
Name: runs, dtype: int64

In [ ]:
#Clips the numbers in two number
subs.clip(100,200)

0      100
1      100
2      100
3      100
4      100
      ...
360    200
361    200
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [ ]:
#Drops duplicate values
temp.drop_duplicates()

0    1
2    2
4    3
6    4
dtype: int64

In [ ]:
#Finds out the number of duplicated values
vk.duplicated().sum()

np.int64(137)

In [ ]:
tempo= pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
tempo

0     1.0
1     2.0
2     3.0
3     NaN
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [ ]:
#Returns the size including the missing values
tempo.size

10

In [ ]:
#Returns the size without the missing values
tempo.count()

np.int64(7)

In [ ]:
#Finds out number of null values
tempo.isnull().sum()

np.int64(3)

In [ ]:
#Drops missing values
temp.dropna()

In [ ]:
#Fills missing value by a targetted number
temp.fillna(temp.mean())

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [ ]:
#Finds out the indices of targetted number
vk[vk.isin([49,99])]

match_no
86    49
82    99
Name: runs, dtype: int64

In [ ]:
#Applies a specific function with specific logics
movies.apply(lambda x:x.split()[0].upper())

movie
Zor Lagaa Ke...Haiya!         MEGHAN
Zokkomon                    DARSHEEL
Zindagi Tere Naam             MITHUN
Zindagi Na Milegi Dobara     HRITHIK
Zindagi 50-50                  VEENA
                              ...
2 States (2014 film)            ALIA
1971 (2007 film)               MANOJ
1920: The Evil Returns         VICKY
1920: London                 SHARMAN
1920 (film)                 RAJNIESH
Name: lead, Length: 1500, dtype: object

In [ ]:
subs.apply(lambda x:'good day' if x > subs.mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [ ]:
#Creates a copy of data
new = vk.head().copy()
new[1] = 100

In [ ]:
print(new)
print(vk)

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64
match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64